Sender: LSF System <lsfadmin@eu-ms-027-32>
Subject: Job 130937300: <python3 rbergomi_dnn_m2.py> in cluster <euler> Exited

Job <python3 rbergomi_dnn_m2.py> was submitted from host <eu-login-05> by user <robinvo> in cluster <euler> at Sat Jul 11 18:24:20 2020
Job was executed on host(s) <eu-ms-027-32>, in queue <normal.24h>, as user <robinvo> in cluster <euler> at Sat Jul 11 18:24:27 2020
</cluster/home/robinvo> was used as the home directory.
</cluster/home/robinvo/rv_bachelor_thesis/Rough_Bergomi_Experiments> was used as the working directory.
Started at Sat Jul 11 18:24:27 2020
Terminated at Sat Jul 11 18:46:08 2020
Results reported at Sat Jul 11 18:46:08 2020

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
python3 rbergomi_dnn_m2.py
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   1299.12 sec.
    Max Memory :                                 3536 MB
    Average Memory :                             1864.98 MB
    Total Requested Memory :                     1024.00 MB
    Delta Memory :                               -2512.00 MB
    Max Swap :                                   -
    Max Processes :                              3
    Max Threads :                                15
    Run time :                                   1310 sec.
    Turnaround time :                            1308 sec.

The output (if any) follows:

W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
0 	RMSE: 0.29459
1 	RMSE: 0.29366
2 	RMSE: 0.327216
3 	RMSE: 0.392646
4 	RMSE: 0.351282
5 	RMSE: 0.194296
6 	RMSE: 0.269658
7 	RMSE: 0.222529
8 	RMSE: 0.246379
9 	RMSE: 0.18223
10 	RMSE: 0.326111
11 	RMSE: 0.430187
12 	RMSE: 0.091776
13 	RMSE: 0.183283
14 	RMSE: 0.218427
15 	RMSE: 0.167424
16 	RMSE: 0.0992045
17 	RMSE: 0.16966
18 	RMSE: 0.174228
19 	RMSE: 0.205925
`xtol` termination condition is satisfied.
Function evaluations 26, initial cost 1.6483e-02, final cost 4.7306e-03, first-order optimality 1.34e-03.
Traceback (most recent call last):
  File "rbergomi_dnn_m2.py", line 376, in <module>
    fig = plt.figure(figsize=(20,6))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
