Sender: LSF System <lsfadmin@eu-ms-007-22>
Subject: Job 129787985: <python3 ../dnn_m1e.py> in cluster <euler> Exited

Job <python3 ../dnn_m1e.py> was submitted from host <eu-login-07> by user <robinvo> in cluster <euler> at Thu Jul  2 10:49:56 2020
Job was executed on host(s) <eu-ms-007-22>, in queue <normal.24h>, as user <robinvo> in cluster <euler> at Thu Jul  2 10:50:04 2020
</cluster/home/robinvo> was used as the home directory.
</cluster/home/robinvo/rv_bachelor_thesis/Heston_SLV_Experiments/run> was used as the working directory.
Started at Thu Jul  2 10:50:04 2020
Terminated at Thu Jul  2 12:39:34 2020
Results reported at Thu Jul  2 12:39:34 2020

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
python3 ../dnn_m1e.py
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   6569.20 sec.
    Max Memory :                                 399 MB
    Average Memory :                             362.56 MB
    Total Requested Memory :                     1024.00 MB
    Delta Memory :                               625.00 MB
    Max Swap :                                   -
    Max Processes :                              3
    Max Threads :                                15
    Run time :                                   6585 sec.
    Turnaround time :                            6578 sec.

The output (if any) follows:

W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/__init__.py:1401: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
0 	RMSE: 0.128808
1 	RMSE: 0.125122
2 	RMSE: 0.128127
3 	RMSE: 0.125119
4 	RMSE: 0.12163
5 	RMSE: 0.118442
6 	RMSE: 0.116105
7 	RMSE: 0.120877
8 	RMSE: 0.118739
9 	RMSE: 0.119207
10 	RMSE: 0.11107
11 	RMSE: 0.108077
12 	RMSE: 0.114643
13 	RMSE: 0.111035
14 	RMSE: 0.109305
15 	RMSE: 0.106603
16 	RMSE: 0.103522
17 	RMSE: 0.107596
18 	RMSE: 0.103324
19 	RMSE: 0.105123
20 	RMSE: 0.103974
21 	RMSE: 0.10321
22 	RMSE: 0.1027
23 	RMSE: 0.102115
24 	RMSE: 0.105005
25 	RMSE: 0.101959
26 	RMSE: 0.0997138
27 	RMSE: 0.095706
28 	RMSE: 0.0974806
29 	RMSE: 0.0963498
30 	RMSE: 0.100427
31 	RMSE: 0.0951801
32 	RMSE: 0.0903079
33 	RMSE: 0.0950246
34 	RMSE: 0.0917206
35 	RMSE: 0.0928027
36 	RMSE: 0.0939388
37 	RMSE: 0.0926278
38 	RMSE: 0.0899472
39 	RMSE: 0.0886445
40 	RMSE: 0.0880686
41 	RMSE: 0.089673
42 	RMSE: 0.0889526
43 	RMSE: 0.0876414
44 	RMSE: 0.0869637
45 	RMSE: 0.0856208
46 	RMSE: 0.0848057
47 	RMSE: 0.083888
48 	RMSE: 0.0838218
49 	RMSE: 0.0830054
`xtol` termination condition is satisfied.
Function evaluations 23, initial cost 8.3047e-05, final cost 8.3047e-05, first-order optimality 1.80e-02.
`xtol` termination condition is satisfied.
Function evaluations 27, initial cost 1.9852e-04, final cost 1.4290e-04, first-order optimality 3.02e-02.
`xtol` termination condition is satisfied.
Function evaluations 23, initial cost 1.1551e-04, final cost 1.1533e-04, first-order optimality 1.16e-03.
Traceback (most recent call last):
  File "../dnn_m1e.py", line 289, in <module>
    fig = plt.figure(figsize=(20, 6))
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/cluster/apps/python/3.6.0/x86_64/lib64/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
